version: "3"
services:
  frontend:
    container_name: ng-powierzenia3000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    ports:
      - 80:3000
  mysql:
    container_name: db-powierzenia
    build: 
      dockerfile: Dockerfile
      context: ./database/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    command: --innodb_use_native_aio=0
    cap_add:
      - SYS_NICE
  backend:
    container_name: powierzenia3000
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/
    ports:
      - 8080:8080
    depends_on:
      - mysql
